export const year = [
  {
    year: "2018",
    desc: "Pre-Debut",
    content: [
      {
        id: 1,
        img: "",
        description: "",
        video: "",
        link: "",
        date: "",
      },
      {
        id: 2,
        img: "",
        description: "",
        video: "",
        link: "",
        date: "",
      },
      {
        id: 3,
        img: "",
        description: "",
        video: "",
        link: "",
        date: "",
      },
    ],
  },

  {
    year: "2019",
    desc: "Debut Year",
    content: [
      {
        id: 1,
        img: "",
        description: "",
        video: "",
        link: "",
        date: "",
      },
      {
        id: 2,
        img: "",
        description: "",
        video: "",
        link: "",
        date: "",
      },
      {
        id: 3,
        img: "",
        description: "",
        video: "",
        link: "",
        date: "",
      },
    ],
  },

  {
    year: "2020",
    desc: "",
    content: [
      {
        id: 1,
        img: "",
        description: "",
        video: "",
        link: "",
        date: "",
      },
      {
        id: 2,
        img: "",
        description: "",
        video: "",
        link: "",
        date: "",
      },
      {
        id: 3,
        img: "",
        description: "",
        video: "",
        link: "",
        date: "",
      },
    ],
  },

  {
    year: "2021",
    desc: "",
    content: [
      {
        id: 1,
        img: "",
        description: "",
        video: "",
        link: "",
        date: "",
      },
      {
        id: 2,
        img: "",
        description: "",
        video: "",
        link: "",
        date: "",
      },
      {
        id: 3,
        img: "",
        description: "",
        video: "",
        link: "",
        date: "",
      },
    ],
  },
  {
    year: "2022",
    desc: "",
    content: [
      {
        id: 1,
        img: "",
        description: "",
        video: "",
        link: "",
        date: "",
      },
      {
        id: 2,
        img: "",
        description: "",
        video: "",
        link: "",
        date: "",
      },
      {
        id: 3,
        img: "",
        description: "",
        video: "",
        link: "",
        date: "",
      },
    ],
  },
];
